### PR TITLE
Allow non square input size

### PR DESCRIPTION
**Pull request by Zellius**
I have YOLOv4 model with non square input layer. This pull request will allow such models.

- To set square input size:

```bash
python save_model.py --input_size 416
```

- To set non square input size:

```bash
python save_model.py --input_size 416x640
```

Other Python scripts use the same format.

### CODE REVIEW

**Comment by alexanderswerdlow** [comment]
I get `ValueError: cannot reshape array of size 767781 into shape (256,384,3,3)` testing on the latest commit.

I ran this command: `python save_model.py --weights yolo-tiny-v4-obj_final.weights --output ./checkpoints/yolov4-tiny-416 --input_size 256x416 --model yolov4 --tiny`.

**Comment by Zellius** [comment]
@alexanderswerdlow Hi!

What is the shape of your YOLO model input layer? Is your input images width == 256 and height == 416?

In my case I have YOLOv4-tiny model trained on my own custom data with input shape `(736, 480, 3)` where (img_height, img_width, img_channels). To convert it to Tensorflow model I'm using command `python ./save_model.py --weights ./weights/yolo-obj_final.weights --output ./weights/tf --input_size 480x736 --model yolov4 --tiny`.

**Comment by alexanderswerdlow** [comment]
Hi @Zellius!

My shape is actually 416x256 (height, width, also with 3 channels), I just tried entering it flipped as a sanity check. Running my validation set with darknet works just fine so I while it certainly could be an issue with my model config, at the very least it runs as expected with Darknet.

Would you mind sharing your cfg file for your model so I could try replicating your results? I think as long as my model is in the same format as yours it won't matter if I only train for a couple iterations.

Here's a bit more of my error message—it occurs in util.py while saving:
```
  File "save_model.py", line 51, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "tensorflow-yolov4-tflite/core/utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 767781 into shape (256,384,3,3)
```

**Comment by mazatov** [comment]
I was looking exactly for this. I do still get the error like the other guys here @Zellius @alexanderswerdlow. Looks liike there's something in the model itself that needs to be adjusted based on the input size...

```
(tf23) C:\Users\Popeye\Documents\Python-projects\tensorflow-yolov4-tflite-master_zell>python save_model.py --weights data\yolov4ball448_800anchor_ball_best.weights --output data\yolov4ball448_800 --input_size 800x448 --model yolov4
2020-08-31 10:32:35.737385: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-31 10:32:35.740451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-08-31 10:32:37.799679: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-08-31 10:32:37.839216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.56GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-08-31 10:32:37.845836: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-08-31 10:32:37.855527: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-08-31 10:32:37.864953: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-08-31 10:32:37.868848: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-08-31 10:32:37.878537: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-08-31 10:32:37.884109: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-08-31 10:32:37.905312: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-08-31 10:32:37.907597: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-08-31 10:32:37.919224: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-31 10:32:37.940629: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f89b9e8a10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-31 10:32:37.944197: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-31 10:32:37.950255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-31 10:32:37.953129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
Traceback (most recent call last):
  File "save_model.py", line 60, in <module>
    app.run(main)
  File "C:\Users\Popeye\Anaconda3\envs\tf23\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Popeye\Anaconda3\envs\tf23\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 56, in main
    save_tf()
  File "save_model.py", line 51, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "C:\Users\Popeye\Documents\Python-projects\tensorflow-yolov4-tflite-master_zell\core\utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 4554552 into shape (1024,512,3,3)

```

**Comment by Zellius** [comment]
@alexanderswerdlow I'm sorry for the late response.
My Darknet config is pretty much default.

<details>
  <summary>YOLOv4 TINY config (single object class)</summary>

  ```
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=16
width=480
height=736
channels=3
momentum=0.9
decay=0.0005
angle=15
saturation = 1.5
exposure = 1.5
hue=.1
gaussian_noise=1

learning_rate=0.00261
burn_in=1000
max_batches = 6000
policy=steps
steps=4800,5400
scales=.1,.1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=2
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=32
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=64
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=64
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[route]
layers=-1
groups=2
group_id=1

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=128
size=3
stride=1
pad=1
activation=leaky

[route]
layers = -1,-2

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[route]
layers = -6,-1

[maxpool]
size=2
stride=2

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

##################################

[convolutional]
batch_normalize=1
filters=256
size=1
stride=1
pad=1
activation=leaky

[convolutional]
batch_normalize=1
filters=512
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear



[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=1
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6

[route]
layers = -4

[convolutional]
batch_normalize=1
filters=128
size=1
stride=1
pad=1
activation=leaky

[upsample]
stride=2

[route]
layers = -1, 23

[convolutional]
batch_normalize=1
filters=256
size=3
stride=1
pad=1
activation=leaky

[convolutional]
size=1
stride=1
pad=1
filters=18
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=1
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6
  ```
</details>

<details>
  <summary>config.py</summary>

  ```python
__C.YOLO.CLASSES              = "./obj.names"
__C.YOLO.ANCHORS              = [12,16, 19,36, 40,28, 36,75, 76,55, 72,146, 142,110, 192,243, 459,401]
__C.YOLO.ANCHORS_V3           = [10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326]
__C.YOLO.ANCHORS_TINY         = [10,14, 23,27, 37,58, 81,82, 135,169, 344,319]
__C.YOLO.STRIDES              = [8, 16, 32]
__C.YOLO.STRIDES_TINY         = [16, 32]
__C.YOLO.XYSCALE              = [1.2, 1.1, 1.05]
__C.YOLO.XYSCALE_TINY         = [1.05, 1.05]
__C.YOLO.ANCHOR_PER_SCALE     = 3
__C.YOLO.IOU_LOSS_THRESH      = 0.5
  ```
</details>

@alexanderswerdlow @mazatov Can you please compare your configs with mine? As I understand it, the most important thing here is to have same dimensions and values for `ANCHORS_TINY` and `anchors` (in the [yolo] layer), `XYSCALE_TINY` and `scale_x_y`(in each [yolo] layer) and `CLASSES` obviously.

I hope it will help you somehow.

**Comment by mazatov** [comment]
@Zellius thanks for the tip! Changing `config.py` did the trick. 

Btw were you able to run images in batch?

**Comment by mazatov** [comment]
I've been doing some more testing. The detections look correct, but the bounding boxes are slightly different from running the darknet on the same image. Wonder what might be causing the discrepancy?

**Comment by Zellius** [comment]
@mazatov 

> Btw were you able to run images in batch?

Yes, I was able to set batch size and run result model on mobile device using tflite 2.2.0. You can check this commit which I use for my project: zellius@dd2d141acfb86a05f0440d9fd647710eaf93743d. But I've changed output tensors there.

Main idea:

- Set correct [batch size](https://github.com/Zellius/tensorflow-yolov4-tflite/blob/dd2d141acfb86a05f0440d9fd647710eaf93743d/save_model.py#L22).

- Set correct batch size in [decode_tflite](https://github.com/Zellius/tensorflow-yolov4-tflite/blob/dd2d141acfb86a05f0440d9fd647710eaf93743d/core/yolov4.py#L249-L281).

- Use Tensorflow's [map_fn](https://github.com/Zellius/tensorflow-yolov4-tflite/blob/dd2d141acfb86a05f0440d9fd647710eaf93743d/core/yolov4.py#L380) to iterate over each batch and apply Non Max Supression to output tensors.

But result model cannot be reshaped using [resize_tensor_input](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#resize_tensor_input).

I'm not a ML/Tensorflow expert, so there may be another better way to do it :smiley: 

> I've been doing some more testing. The detections look correct, but the bounding boxes are slightly different from running the darknet on the same image. Wonder what might be causing the discrepancy?

Did you change your`config.py` variables using mine values or your own? You should use correct values from your own YOLO config which was used during train process. I'm using `--quantize_mode float16` during convert and can't find visual difference in my case. I'm not sure if I can help here, sorry.

**Comment by mazatov** [comment]
> Did you change your`config.py` variables using mine values or your own? You should use correct values from your own YOLO config which was used during train process. I'm using `--quantize_mode float16` during convert and can't find visual difference in my case. I'm not sure if I can help here, sorry.

I changed the .data file and the anchors. Not sure about the other ones. I haven't changed them in the darknet config either. Would they be different? Do you know here in the darknet `*.cfg` file would I find them?

Thanks for the tips! I'll try batch processing a bit later.

**Pull request closed without merging**
